[package]
name = "main-app"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.0"
chess = { path = "../chess" }
chess-ai = { path = "../chess-ai" }
anyhow = "1.0.79"
sdl2 = { version = "0.36.0", features = ["bundled", "ttf", "image"] }
