[package]
name = "main-app"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.0"
sdl2-app = { path = "../sdl2-app" }
chess = { path = "../chess" }
chess-ai = { path = "../chess-ai" }
anyhow = "1.0.79"
